apiVersion: v1
kind: Service
metadata:
  name: web-app
spec:
  selector:
    app: web-app
  ports:
    - name: http
      port: 80
      targetPort: 14450
    - name: https
      port: 443
      targetPort: 14450
  type: LoadBalancer
